[package]
name = "io_macro"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "parsing"] }
quote = "1.0"
